### PR TITLE
Create a README file for the project, as well as license.

### PR DESCRIPTION
**Pull request by Notoh**
In issues I read that this was needed, so hopefully this helps.

### CODE REVIEW

**Comment by MinnDevelopment** [comment]
Maybe we should license this under GPL3?

**Comment by MinnDevelopment** [comment]
The classes itself have Apache 2.0 license headers which need to either be replaced or removed if we use a different license

**Comment by Notoh** [comment]
I'm not sure about License, I just chose MIT because its what RPC itself is licensed under, and seeing that this is a binding of RPC it would make sense to have a shared license.
Totally up to you though, you are the author after all.

**Comment by MinnDevelopment** [comment]
I'd be in favor of using the Apache License 2.0

**Comment by Notoh** [comment]
Alright, I'll change it on my fork then you can merge.

**Review by MinnDevelopment — APPROVED** [review]

**Pull request merged**
