### PR TITLE
Unicode support

### PR DESCRIPTION
**Pull request by CertainLach**

### CODE REVIEW

**Comment by MinnDevelopment** [comment]
I don't have this issue at all with the current master version.
image

**Comment by MinnDevelopment** [comment]
I'm unsure if this is the right way to "fix" an issue that is not present for me.
Could this be related to the file encoding in your application?

If you find a better solution, maybe `-Dfile.encoding=utf8` I would accept a change to the README hinting at the solution.

**Comment by MinnDevelopment** [comment]
Any update on this?

**Comment by ImagePrototype** [comment]
I have the same problem. Is there a solution? Why the encoding breaks if state is set on the client side. What is important is that when the launch comes from IDEA - everything is fine, and as soon as the client starts - the problem.

**Pull request closed without merging**
